### ISSUE TITLE
Can't 'lein run' rhombrick

### ISSUE THREAD

**Issue by jonoflayham** [julesb/rhombrick#2]
On MacOS 10.11.3 (El Capitan) and MacOS 10.10.5 (Yosemite) with Oracle JDK 1.8.0_71, I can't use run rhombrick using 'lein run'.

On the `topology` branch, I get

`java.io.FileNotFoundException: data/rhombrick-boundary.obj (No such file or directory), compiling:(tiling_render.clj:52:41)`

while on `master`, I get a lot of reflection warnings and a new Java process ('main'), but no display.

**Comment by julesb** [comment]
Thanks for your interest! I've added the missing assets. A fresh clone of the repo should now run ok on jdk 1.6 but doesn't seem to be currently working with any later version. It was working on 1.7 previously so not sure what the issue is but I doubt it will be a big deal so I'll update this issue a bit later when I've had a look into it.

You definitely want the topology branch, all the other branches are pretty old and I've not tried running any of them for ages.

**Comment by jonoflayham** [comment]
Pleasure - I'm looking forward to some mouth-watering graphics!   I'll give it a try on 1.6.

fwiw, I tried `lein uberjar` and even just `lein jar` - still under Java 8 - and in both cases after a bit of lein activity the 'main' process started and nothing else happened.

**Comment by jonoflayham** [comment]
fwiw I can run rhombrick.core/main- directly from a Cursive-provided REPL in IntelliJ with Java 8, and stuff actually appears.

Hmm.  This worked once, but I can't get it to work again, even with IntelliJ restarts.

**Comment by julesb** [comment]
I've removed some old stuff which is not needed and now 'lein run' works using jdk 1.7 and 1.8. There is still a problem with 1.8 where the jvm segfaults when closing the quil window, so I'd recommend using 1.7 for now. Good luck, and don't hesitate to ask if you have any questions.

**Comment by jonoflayham** [comment]
Fantastic - thanks very much.  I'm looking forward to having a play.

**Comment by julesb** [comment]
I was just checking over things as I haven't used it for a while and I found a problem with the tiler so you should you pull the latest changes, or the tilings wont be generated properly. I also improved a couple of default settings. The graphical tile editing is broken, but you can set the tileset at a REPL with for example:
`(set-tileset ["--------6-cC" "------cC--4-" "---------14-"])`

To get started you can use `<` and `>` keys to step through the saved tilesets.

**Comment by jonoflayham** [comment]
It's working beautifully now, and even using Oracle Java 1.8 I'm not seeing any obvious failures.  Mesmerising!
